language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

script: ./vendor/bin/tester ./tests/cases

after_failure:
    # Print *.actual content & log content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
    - for i in $(find tests -name \*.log); do echo "--- $i"; cat $i; echo; echo; done

before_script:
    # Install Nette Tester
    - composer install --no-interaction --dev --prefer-source
